feat(wpctl): add a runtime dependency check
Check at the begining of the wpctl script if the required commands are
installed and exit with error if not.

diff --git a/wpctl b/wpctl
--- a/wpctl
+++ b/wpctl
@@ -656,6 +656,14 @@ if [ ${OPTION_DEBUG} = 1 ] ; then
     set -x
 fi
 
+if ! command -v perl > '/dev/null' 2> '/dev/null' ; then
+    fatal "cannot find 'perl' command"
+fi
+
+if ! command -v mysql > '/dev/null' 2> '/dev/null' ; then
+    fatal "cannot find 'mysql' command"
+fi
+
 if [ $# -lt 1 ] ; then
     fatal "missing operation argument"
 fi
